version: '3'

services:
  import_map:
    image: overv/openstreetmap-tile-server
    container_name: osm-tile-server-import
    volumes:
      - /home/data/osm/germany-latest.osm.pbf:/data/germany-latest.osm.pbf
      - osm-data:/data/database/
    command: "import"

  run_map:
    image: overv/openstreetmap-tile-server
    container_name: osm-tile-server-run
    volumes:
      - osm-data:/data/database/
    ports:
      - "8080:80"
    command: "run"

volumes:
  osm-data:
    external: true
